### PR TITLE
Update log message.

### PR DESCRIPTION
**Pull request by lli-parasoft**

### CODE REVIEW

**Comment by lli-parasoft** [comment]
Updated log is :
image

**Comment by yshi-parasoft** [comment]
> Updated log is : image

Let's remove the sentence "Please try recreate ..."
Then print the exception name and error message.
Then print the suggestion to recreate the report or see logs.
So the example in the screenshot will look like:
```
Unexpected report format: xxxx
xxxException: Content is not allowed in prolog. 
Please try recreating the report or see log for details: xxx.
```
Can you please research on the reason for printing "Failed to parse XML report" twice?

**Comment by lli-parasoft** [comment]
For printing "Failed to parse XML report" twice, this message are printed by  `_build.getBuildLogger().buildFailureDescription(description);`
But this line are only called once. I believe this problem is caused by buildFailureDescription(). Need to continue research.

**Review by yshi-parasoft — APPROVED** [review]

**Comment by yshi-parasoft** [comment]
image
It looks good to me now. I'll merge this, and we don't need to research on the duplicates since it's behavior of TeamCity. I see a question is open:
https://teamcity-support.jetbrains.com/hc/en-us/community/posts/4408148592658-buildFailureDescription-duplicate-entry-

**Pull request merged**
